# Generated by Django 4.0 on 2022-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnibarchart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordata',
            name='year',
            field=models.CharField(choices=[('YR2000', '2000'), ('YR2002', '2002'), ('YR2004', '2004'), ('YR2006', '2006'), ('YR2008', '2008'), ('YR2010', '2010'), ('YR2012', '2012'), ('YR2014', '2014'), ('YR2016', '2016'), ('YR2018', '2018')], max_length=50),
        ),
    ]
